name: Sync to GitLab

on:
  push:
    branches:
      - main  # Adjust this if you use a different default branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Add GitLab remote
      run: |
        git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.pavlovia.org/cadurdle/IRoR_Descriptions_Congruent_s1-2.git

    - name: Fetch from GitLab
      run: |
        git fetch gitlab main

    - name: Merge GitLab changes with ours
      run: |
        git merge gitlab/main --allow-unrelated-histories -s ours

    - name: Debug Info
      run: |
        git remote -v
        git branch -a
        git log -n 5

    - name: Push to GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        git push -u gitlab main
